name: Build and Deploy (Docker Alternative)
on:
  workflow_dispatch: # Manual trigger only as backup

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-docker"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.2-alpine
    steps:
      - name: Install system dependencies
        run: |
          apk add --no-cache build-base git imagemagick vips

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Ruby dependencies
        run: |
          gem install bundler
          bundle config set --local deployment false
          bundle config set --local frozen false
          bundle install

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build site
        run: |
          bundle exec jekyll build --destination ./_site --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
